spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jwt_security
    username: root
    password : Dharma2018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port : 8080
